### ISSUE TITLE
Security Data Issues Secrets in clear text

### ISSUE THREAD

**Issue by shaybenb** [HugoLeBoennec/projetData#1]
Hi,<br><br>url : https://github.com/HugoLeBoennec/projetData/blob/eb5a95ac628a1dac35e75282d7f104bcc17a32f3/livrable%201%20partie%206.html <br><br>You have commit that need to remove from the github history<br>attacker can see it and use it ...<br><br>encrypt your secrets !!!!<br><br>Our Bug Help you to be more Secure and protect your data ?<br>Buy me a coffee (or more likely a beer)<br>https://www.paypal.com/paypalme/bugbounty1/150USD<br>https://www.buymeacoffee.com/bugbounty<br>☕☕☕☕☕

**Comment by HugoLeBoennec** [comment]
I didn't found where are they, please give more information

**Comment by shaybenb** [comment]
![image](https://user-images.githubusercontent.com/46863888/104811509-a964c880-5804-11eb-8462-230435cb5753.png)

**Comment by shaybenb** [comment]
Our Bug Help you to be more Secure and protect your data ?
Buy me a coffee (or more likely a beer)
https://www.paypal.com/paypalme/bugbounty1/150USD
https://www.buymeacoffee.com/bugbounty
☕☕☕☕☕
